server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/before30/home/tree/master/config-repo
          basedir: target/config
---

spring:
  profiles: development
server:
  port: 8080

---

spring:
  profiles: production
server:
  port: 8080
