server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  boot:
    admin:
      url: http://localhost:8081
  cloud:
    config:
      server:
        git:
          uri: https://github.com/before30/home/tree/master/config-repo
          basedir: target/config
---

spring:
  profiles: development
server:
  port: 8080

---

spring:
  profiles: production
server:
  port: 8080
