apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reactive-demo-service-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: reactive-demo-service
    spec:
      containers:
      - name: reactive-demo-service
        image: cc.before30.home/reactive-demo:latest
        ports:
        - containerPort: 8080